version: 2.1
orbs:
  zulip: ponylang/zulip@1

jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test examples
      - zulip/status:
          fail_only: true
  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - run: apt-get update
      - run: apt-get install -y libpcre2-dev libssl-dev
      - checkout
      - run: make test examples
      - zulip/status:
          fail_only: true


workflows:
  version: 2
  commit:
    jobs:
    - vs-ponyc-master:
        context: org-global
